{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/naveenk-DS/Selenium_Redbus_DataScraping.app.py/blob/main.py/Selenium_Redbus_DataScraping.app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! pip install selenium pandas streamlit beautifulsoup4 lxml\n"
      ],
      "metadata": {
        "collapsed": true,
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "TJLagu9vPur3",
        "outputId": "fe26814a-afb5-4a2b-a723-1a31c4820f5a"
      },
      "id": "TJLagu9vPur3",
      "execution_count": 29,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: selenium in /usr/local/lib/python3.11/dist-packages (4.34.2)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)\n",
            "Collecting streamlit\n",
            "  Downloading streamlit-1.46.1-py3-none-any.whl.metadata (9.0 kB)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (4.13.4)\n",
            "Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (5.4.0)\n",
            "Requirement already satisfied: urllib3~=2.5.0 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.5.0->selenium) (2.5.0)\n",
            "Requirement already satisfied: trio~=0.30.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.30.0)\n",
            "Requirement already satisfied: trio-websocket~=0.12.2 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.12.2)\n",
            "Requirement already satisfied: certifi>=2025.6.15 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.7.9)\n",
            "Requirement already satisfied: typing_extensions~=4.14.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (4.14.1)\n",
            "Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)\n",
            "Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.2.1)\n",
            "Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (24.2)\n",
            "Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (11.2.1)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.11/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.11/dist-packages (from streamlit) (2.32.3)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit) (8.5.0)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit) (0.10.2)\n",
            "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
            "  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.3/44.3 kB\u001b[0m \u001b[31m475.9 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.11/dist-packages (from streamlit) (3.1.44)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit) (6.4.2)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (2.7)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (4.24.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit) (1.46.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
            "Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (25.3.0)\n",
            "Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (2.4.0)\n",
            "Requirement already satisfied: outcome in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.0.post0)\n",
            "Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.1)\n",
            "Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.11/dist-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)\n",
            "Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.5.0->selenium) (1.7.1)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2025.4.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.26.0)\n",
            "Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)\n",
            "Downloading streamlit-1.46.1-py3-none-any.whl (10.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.1/10.1 MB\u001b[0m \u001b[31m22.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m59.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m79.1/79.1 kB\u001b[0m \u001b[31m5.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: watchdog, pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.46.1 watchdog-6.0.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from selenium import webdriver\n",
        "from selenium.webdriver.common.by import By\n",
        "from selenium.webdriver.chrome.options import Options\n",
        "import pandas as pd\n",
        "import time\n",
        "import os"
      ],
      "metadata": {
        "id": "6PDvPpP2Pyic"
      },
      "id": "6PDvPpP2Pyic",
      "execution_count": 33,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from selenium import webdriver\n",
        "from selenium.webdriver.common.by import By\n",
        "from selenium.webdriver.chrome.options import Options\n",
        "import pandas as pd\n",
        "import time\n",
        "import os\n",
        "import streamlit as st\n",
        "\n",
        "def scrape_redbus_data(from_city='Chennai', to_city='Bangalore', date='16-Jul-2025'):\n",
        "    options = Options()\n",
        "    options.add_argument(\"--headless\")\n",
        "    driver = webdriver.Chrome(options=options)\n",
        "\n",
        "    url = 'https://www.redbus.in/'\n",
        "    driver.get(url)\n",
        "    time.sleep(2)\n",
        "\n",
        "    # Fill in From and To fields\n",
        "    driver.find_element(By.ID, \"src\").send_keys(from_city)\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, \"//li[text()='{}']\".format(from_city)).click()\n",
        "\n",
        "    driver.find_element(By.ID, \"dest\").send_keys(to_city)\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, \"//li[text()='{}']\".format(to_city)).click()\n",
        "\n",
        "    # Set date\n",
        "    driver.find_element(By.ID, \"onward_cal\").click()\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, f\"//td[@class='wd day' or @class='we day' or @class='current day' or @class='day'][text()='{int(date.split('-')[0])}']\").click()\n",
        "\n",
        "    driver.find_element(By.ID, \"search_btn\").click()\n",
        "    time.sleep(5)\n",
        "\n",
        "    buses = driver.find_elements(By.XPATH, '//div[@class=\"travels lh-24 f-bold d-color\"]')\n",
        "    prices = driver.find_elements(By.XPATH, '//div[@class=\"fare d-block\"]')\n",
        "    timings = driver.find_elements(By.XPATH, '//div[@class=\"dp-time f-19 d-color f-bold\"]')\n",
        "\n",
        "    bus_names, ticket_prices, departure_times = [], [], []\n",
        "\n",
        "    for i in range(min(len(buses), len(prices), len(timings))):\n",
        "        bus_names.append(buses[i].text.strip())\n",
        "        ticket_prices.append(prices[i].text.strip().replace('₹', ''))\n",
        "        departure_times.append(timings[i].text.strip())\n",
        "\n",
        "    driver.quit()\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        'Bus Operator': bus_names,\n",
        "        'Price': ticket_prices,\n",
        "        'Departure Time': departure_times,\n",
        "        'From': from_city,\n",
        "        'To': to_city,\n",
        "        'Date': date\n",
        "    })\n",
        "\n",
        "    output_dir = r'E:\\Naveen\\Scrap data'\n",
        "    os.makedirs(output_dir, exist_ok=True)\n",
        "    df.to_csv(os.path.join(output_dir, 'redbus_data.csv'), index=False)\n",
        "    return df\n",
        "\n",
        "\n",
        "st.set_page_config(page_title=\"Redbus Data Viewer\", layout=\"wide\")\n",
        "\n",
        "st.title(\"🚌 Redbus Data Scraper & Filter App\")\n",
        "\n",
        "from_city = st.text_input(\"From City\", \"Chennai\")\n",
        "to_city = st.text_input(\"To City\", \"Bangalore\")\n",
        "date = st.date_input(\"Travel Date\").strftime(\"%d-%b-%Y\")\n",
        "\n",
        "if st.button(\"Scrape Redbus Data\"):\n",
        "    with st.spinner(\"Scraping in progress...\"):\n",
        "        df = scrape_redbus_data(from_city, to_city, date)\n",
        "        st.success(\"Scraping completed! ✅\")\n",
        "        st.dataframe(df)\n",
        "\n",
        "        # Save path confirmation\n",
        "        st.info(f\"Data saved to: `E:\\\\Naveen\\\\Scrap data\\\\redbus_data.csv`\")\n",
        "\n",
        "# Load data if already scraped\n",
        "try:\n",
        "    df = pd.read_csv(r\"E:\\Naveen\\Scrap data\\redbus_data.csv\")\n",
        "    st.subheader(\"📊 Filter Scraped Redbus Data\")\n",
        "\n",
        "    # Filters\n",
        "    selected_operator = st.multiselect(\"Select Bus Operator(s)\", options=df[\"Bus Operator\"].unique())\n",
        "    selected_price = st.slider(\"Select Price Range\", int(df[\"Price\"].min()), int(df[\"Price\"].max()))\n",
        "\n",
        "    filtered_df = df.copy()\n",
        "\n",
        "    if selected_operator:\n",
        "        filtered_df = filtered_df[filtered_df[\"Bus Operator\"].isin(selected_operator)]\n",
        "\n",
        "    filtered_df = filtered_df[filtered_df[\"Price\"].astype(int) <= selected_price]\n",
        "\n",
        "    st.dataframe(filtered_df)\n",
        "\n",
        "except FileNotFoundError:\n",
        "    st.warning(\"No scraped data found. Please scrape first using the above form.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "za8U7eyXP1To",
        "outputId": "6093de07-8737-4f07-bf3d-a5dd28fd47cd"
      },
      "id": "za8U7eyXP1To",
      "execution_count": 35,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-07-14 18:44:52.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.175 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.179 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:44:52.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "from selenium import webdriver\n",
        "from selenium.webdriver.common.by import By\n",
        "from selenium.webdriver.chrome.options import Options\n",
        "import time\n",
        "import os\n",
        "\n",
        "def scrape_redbus_data(from_city='Chennai', to_city='Bangalore', date='16-Jul-2025'):\n",
        "    options = Options()\n",
        "    options.add_argument(\"--headless\")\n",
        "    driver = webdriver.Chrome(options=options)\n",
        "\n",
        "    url = 'https://www.redbus.in/'\n",
        "    driver.get(url)\n",
        "    time.sleep(2)\n",
        "\n",
        "    # Fill in From and To fields\n",
        "    driver.find_element(By.ID, \"src\").send_keys(from_city)\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, \"//li[text()='{}']\".format(from_city)).click()\n",
        "\n",
        "    driver.find_element(By.ID, \"dest\").send_keys(to_city)\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, \"//li[text()='{}']\".format(to_city)).click()\n",
        "\n",
        "    # Set date\n",
        "    driver.find_element(By.ID, \"onward_cal\").click()\n",
        "    time.sleep(1)\n",
        "    driver.find_element(By.XPATH, f\"//td[@class='wd day' or @class='we day' or @class='current day' or @class='day'][text()='{int(date.split('-')[0])}']\").click()\n",
        "\n",
        "    driver.find_element(By.ID, \"search_btn\").click()\n",
        "    time.sleep(5)\n",
        "\n",
        "    buses = driver.find_elements(By.XPATH, '//div[@class=\"travels lh-24 f-bold d-color\"]')\n",
        "    prices = driver.find_elements(By.XPATH, '//div[@class=\"fare d-block\"]')\n",
        "    timings = driver.find_elements(By.XPATH, '//div[@class=\"dp-time f-19 d-color f-bold\"]')\n",
        "\n",
        "    bus_names, ticket_prices, departure_times = [], [], []\n",
        "\n",
        "    for i in range(min(len(buses), len(prices), len(timings))):\n",
        "        bus_names.append(buses[i].text.strip())\n",
        "        ticket_prices.append(prices[i].text.strip().replace('₹', ''))\n",
        "        departure_times.append(timings[i].text.strip())\n",
        "\n",
        "    driver.quit()\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        'Bus Operator': bus_names,\n",
        "        'Price': ticket_prices,\n",
        "        'Departure Time': departure_times,\n",
        "        'From': from_city,\n",
        "        'To': to_city,\n",
        "        'Date': date\n",
        "    })\n",
        "\n",
        "    output_dir = r'E:\\Naveen\\Scrap data'\n",
        "    os.makedirs(output_dir, exist_ok=True)\n",
        "    df.to_csv(os.path.join(output_dir, 'redbus_data.csv'), index=False)\n",
        "    return df\n",
        "\n",
        "\n",
        "st.set_page_config(page_title=\"Redbus Data Viewer\", layout=\"wide\")\n",
        "\n",
        "st.title(\"🚌 Redbus Data Scraper & Filter App\")\n",
        "\n",
        "from_city = st.text_input(\"From City\", \"Chennai\")\n",
        "to_city = st.text_input(\"To City\", \"Bangalore\")\n",
        "date = st.date_input(\"Travel Date\").strftime(\"%d-%b-%Y\")\n",
        "\n",
        "if st.button(\"Scrape Redbus Data\"):\n",
        "    with st.spinner(\"Scraping in progress...\"):\n",
        "        df = scrape_redbus_data(from_city, to_city, date)\n",
        "        st.success(\"Scraping completed! ✅\")\n",
        "        st.dataframe(df)\n",
        "\n",
        "        # Save path confirmation\n",
        "        st.info(f\"Data saved to: `E:\\\\Naveen\\\\Scrap data\\\\redbus_data.csv`\")\n",
        "\n",
        "# Load data if already scraped\n",
        "try:\n",
        "    df = pd.read_csv(r\"E:\\Naveen\\Scrap data\\redbus_data.csv\")\n",
        "    st.subheader(\"📊 Filter Scraped Redbus Data\")\n",
        "\n",
        "    # Filters\n",
        "    selected_operator = st.multiselect(\"Select Bus Operator(s)\", options=df[\"Bus Operator\"].unique())\n",
        "    selected_price = st.slider(\"Select Price Range\", int(df[\"Price\"].min()), int(df[\"Price\"].max()))\n",
        "\n",
        "    filtered_df = df.copy()\n",
        "\n",
        "    if selected_operator:\n",
        "        filtered_df = filtered_df[filtered_df[\"Bus Operator\"].isin(selected_operator)]\n",
        "\n",
        "    filtered_df = filtered_df[filtered_df[\"Price\"].astype(int) <= selected_price]\n",
        "\n",
        "    st.dataframe(filtered_df)\n",
        "\n",
        "except FileNotFoundError:\n",
        "    st.warning(\"No scraped data found. Please scrape first using the above form.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "8w5Tq9_nQCbw",
        "outputId": "14c008d6-d541-496e-c205-47f97aa2bd62"
      },
      "id": "8w5Tq9_nQCbw",
      "execution_count": 38,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-07-14 18:46:11.752 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.763 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.768 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-07-14 18:46:11.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.12.4"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}